 <script type="text/javascript" src="http://www.genstar.com.ua/1280/script/sitefunction.js"></script>
<div id="map_block">
    <div id="center_head_block"><center><font class="content_left_head_font">КАРТА ПРОЕЗДА (КРИНИЧНАЯ)</font></center></div>
    <div id="map_image_block"><center><image src="http://www.genstar.com.ua/1280/img/map_small.jpg" alt="map"  align="left" height="360" width="320"></center></div>
    <div id="big_map_link_block"><center><a href="javascript:openBigMap(1)" class="big_map_link_font">Увеличить</a></center></div>
   </div> 
   <div id="filials_block">
    <div id="filials_head_block">
     <center><font class="content_left_head_font">КОНТАКТЫ</font></center>
     <a href="javascript:showSmallMap(1)" class="content_left_head1_link_font">Криничная :</a> 
    </div>
    <div id="filials_left_block">  
     <font class="content_left_head2_font">Адрес:</font><br>
     <font class="content_left_head2_font">тел.:</font><br>
     <font class="content_left_head2_font">тел./факс:</font><br>
     <font class="content_left_head2_font">моб.тел.:</font><br>
     <font class="content_left_head2_font">email:</font><br>
     <font class="content_left_head2_font">ICQ:</font><br>
    </div>
    <div id="filials_right_block">
      <font class="content_right_text_font"> г. Киев, ул. Криничная, 2</font><br>
      <font class="content_right_text_font">+38(044)223-83-46; +38(044)258-25-88; +38(044)362-60-28</font><br>
      <font class="content_right_text_font">+38(044)258-25-82</font><br>
      <font class="content_right_text_font">+38(050)295-94-56; +38(063)834-84-19; +38(050)368-05-80</font><br>
      <font class="content_right_text_font">genstar@genstar.com.ua</font><br>
      <font class="content_right_text_font">364-935-219</font><br>
    </div>
  
    <div id="filials_head_block">
      <a href="javascript:showSmallMap(2)" class="content_left_head1_link_font">Позняки:</a> 
    </div>
    <div id="filials_left_block">  
     <font class="content_left_head2_font">Адрес:</font><br>
     <font class="content_left_head2_font">тел.:</font><br>
     <font class="content_left_head2_font">email:</font><br>
     <font class="content_left_head2_font">ICQ:</font><br>
    </div>
    <div id="filials_right_block">
      <font class="content_right_text_font">г. Киев, ул. Соломии Крушельницкой (гаражный кооператив)</a>
      <br>
      <font class="content_right_text_font">+38(044)383-25-92;+38(099)224-72-75; +38(093)050-14-50</font>
      <br>
      <font class="content_right_text_font">f1@genstar.com.ua</font>
      <br>
      <font class="content_right_text_font">596-210-354</font>
    </div>

    <div id="filials_head_block">
      <a href="javascript:showSmallMap(3)" class="content_left_head1_link_font">Березка:</a> 
    </div>
    <div id="filials_left_block">  
     <font class="content_left_head2_font">Адрес:</font>
     <br>
     <font class="content_left_head2_font">тел.:</font>
     <br> 
     <font class="content_left_head2_font">email:</font>
     <br> 
     <font class="content_left_head2_font">ICQ:</font>
    </div>
    <div id="filials_right_block">
      <font class="content_right_text_font">г. Киев, ул. Большая Окружная 4Б (гаражный кооператив "Березка2")</font>
      <br>
      <font class="content_right_text_font">+38(044)362-32-41; +38(099)797-74-87; +38(093)093-8-666;</font>
      <br>
      <font class="content_right_text_font">f2@genstar.com.ua</font>
      <br>
      <font class="content_right_text_font">369-662-373</font>
    </div>

    <div id="filials_head_block">
      <a href="javascript:showSmallMap(4)" class="content_left_head1_link_font">Ватутина:</a> 
    </div>
    <div id="filials_left_block">  
       <font class="content_left_head2_font">Адрес:</font>
     <br>
     <font class="content_left_head2_font">тел.:</font>
     <br> 
     <font class="content_left_head2_font">email:</font>
     <br> 
     <font class="content_left_head2_font">ICQ:</font>
    </div>
    <div id="filials_right_block">
      <font class="content_right_text_font"> г. Киев, ул. Ватутина, 104</font>
      <br>
      <font class="content_right_text_font">+38(044)227-54-02; +38(099)730-61-09; +38(093)093-88-14</font>
      <br>
      <font class="content_right_text_font">f3@genstar.com.ua</font>
      <br>
      <font class="content_right_text_font">450-633-465</font>
    </div>

    <div id="filials_head_block">
      <a href="javascript:showSmallMap(7)" class="content_left_head1_link_font">Славутич:</a> 
    </div>
    <div id="filials_left_block">  
       <font class="content_left_head2_font">Адрес:</font>
     <br>
     <font class="content_left_head2_font">тел.:</font>
     <br> 
     <font class="content_left_head2_font">email:</font>
    </div>
    <div id="filials_right_block">
      <font class="content_right_text_font"> г. Киев, ул. Затышная, 7Б</font>
      <br>
      <font class="content_right_text_font">+38(044)360-75-91; +38(093)276-36-60; +38(066)439-23-32</font>
      <br>
      <font class="content_right_text_font">f5@genstar.com.ua</font>
    </div>
