 <?php echo $this->docType('XHTML1_STRICT')?>  
 <html>  
  <head>  
    <meta http-equiv="Content-Type" content="text/html;charset=charset=windows-cp1251" /> 
    <title><?php echo $this->escape($this->title);?></title>   
    <link rel="stylesheet" type="text/css" media="screen"
    href="<?php echo $this->baseUrl;?>/public/styles/main.css" />
   <?php echo $this->headTitle() ?>  
  </head>  
  <body>  
   <div id="head_block">
    <image src="<?php echo $this->baseUrl;?>/public/img/head.jpg" alt="head.jpg" width="1100">
   </div>
    <?php
         //Выдаем меню
         echo "<div id=\"main_manager_block_link\">
           <div id=\"manager_block_link_head\">
            <font class=\"inet_magaizn_link_block_head_font\">
              <center>Главное меню</center>
            </font>
           </div> 
           <div id=\"manager_block_link\">
            &nbsp;<A href=\"/index/\" class=\"inet_magazin_link_box_font\">О компании</a><br>
            &nbsp;<A href=\"/contacts/\" class=\"inet_magazin_link_box_font\">Контакты</a><br>
            &nbsp;<A href=\"/carsa/\" class=\"inet_magazin_link_box_font\">Поис по автомобилю</a><br>
            &nbsp;<A href=\"/oem/\" class=\"inet_magazin_link_box_font\">Поиск по номеру OEM</a><br>
            &nbsp;<A href=\"/help/\" class=\"inet_magazin_link_box_font\">Помощь</a><br>
           </div>
            <div id=\"manager_block_link_head\">
            <font class=\"inet_magaizn_link_block_head_font\">
              <center>Последние 15 запросов </center>
            </font>
           </div>";

         //Выдаем 15 последних запросов
         //Достаем базу из регистра
         require_once 'Zend/Session.php';
         Zend_Session::start();
         $db=Zend_Registry::get('db');
         $select=new Zend_Db_Select($db);
         $select->from("history")
                ->where("sid='".Zend_Session::getId()."'")
                ->limit("15,1")
                ->order("add_date DESC");
         $stmt = $db->query($select);
         $result="";
         while ($row=$stmt->fetch())
           $result=$result."<font class=\"top15FontStyleDate\">".$row['add_date'].
                    "</font>-<font class=\"top15FontStyleNum\">".$row['findnum']."</font><br>";
         
         echo "<div id=\"manager_block_link\">".$result."</div>";
 
         //Выдаем Погоду, курсы валют,счетчики
         echo "<div id=\"manager_block_link_head\">
            <font class=\"inet_magaizn_link_block_head_font\">
              <center>Разное</center>
            </font>
           </div> 
            <div id=\"manager_block_link\">
             <div style=\"overflow: hidden; margin-left:0.5em; height: 115px;\">
<table cellpadding=0 cellspacing=0 width=180 style=\"border:solid 1px #061393;font-family:Arial;font-size:12px;background-color:#f7f7f7\"><tr><td><table width=100% cellpadding=0 cellspacing=0><tr><td width=8 height=30 background=\"http://rp5.ua/informer/htmlinfa/topshl.png\"  bgcolor=#061393> </td><td width=* align=center background=\"http://rp5.ua/informer/htmlinfa/topsh.png\" bgcolor=#061393><a style=\"color:#ffffff; font-family:Arial;font-size: 12px;\" href=\"http://rp5.ua/233/ru\"><b>Киев</b></a></td><td width=8 height=30 background=\"http://rp5.ua/informer/htmlinfa/topshr.png\" bgcolor=#061393> </td></tr></table></td></tr><tr><td valign=top style=\"padding:0;\"><iframe src=\"http://rp5.ua/htmla.php?id=233&lang=ru&bg=%23f7f7f7&ft=%23ffffff&fc=%23061393&c=%23000000&f=Arial&s=12&sc=1\" width=100% height=79 frameborder=0 scrolling=no style=\"margin:0;\"></iframe></td></tr></table>
             </div>
             <div style=\"margin-left:1.10em; margin-top:0.5em;\">
<!-- News Banker -->
<style>
.banker_informer_vert {text-align:left; clear: both; }
</style>
<div class=\"banker_informer_vert_160\" id=\"banker_informer_vert_160\">
<a href=\"http://banker.ua/marketindex/cashcourse/\">Наличные курсы валют</a>
</div>
<!-- Before -->
<script charset=\"utf-8\" language=\"javascript\" src=\"http://banker.ua/js/cur.js\"> </script>
<script> ShowInformer( document.getElementById( \"banker_informer_vert_160\" ), \"\", \"\", \"\", \"\", \"\"); </script>
<!-- News Banker -->
             </div>
            </div>
          </div>";
         //Выдаем главный блок
         echo "<div id=\"manager_block_text\"><div id=\"manager_block_text_child\">";
         echo $this->layout()->content;
         echo "</div></div>";
     ?>  
  </body>  
 </html>  