<!-- Path to jQuery library -->
<?php echo $this->headScript(); ?>
<!-- Path to jQuery-PHP library -->
<?php echo $this->headScript(); ?>
<div id="manger_cars_result_block"><center><font class="content_left_head_font">Поиск деталей по автомобилю <br><?= $this->head_str ?></font></center><br><?= $this->result ?>
</div><div id="manger_cars_find_block"><div style="margin-left:1em"><font class="carsForm"><?= $this->form ?></center></div></div>
